// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for MediaPipelinesFunction
 */
export interface MediaPipelinesFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/resources/media-pipelines/media-pipelines.
 */
export class MediaPipelinesFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: MediaPipelinesFunctionProps) {
    super(scope, id, {
      description: 'src/resources/media-pipelines/media-pipelines.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/resources/media-pipelines/media-pipelines.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}